### PR TITLE
[FIX] Tune idle connection check frequency

### PR DESCRIPTION
**Pull request by razitz**
Reduce the client overhead for connection liveliness checks.

Tuned idle connection ping check threshold from 1 millisecond idle time to 1 minute idle time.
Based on the Redis client code example https://github.com/gomodule/redigo/blob/90a3d85/redis/pool.go#L107

### CODE REVIEW

**Review by filipecosta90 — APPROVED** [review]

**Comment by dengliming** [comment]
It would be better If this is configurable. : )

**Review by dengliming — APPROVED** [review]

**Comment by dengliming** [comment]
@filipecosta90 Can we go on this?

**Comment by filipecosta90** [comment]
> @filipecosta90 Can we go on this?

Yes. Sorry for the delay on this @dengliming and @razitz . Let me double the best way ( if it's this one ) and report back until end of day :)

**Comment by filipecosta90** [comment]
> It would be better If this is configurable. : )

@dengliming I tend to agree but the proper way to do this (or to have 100% control on the connection options) is to create a pool with the settings we want and then use NewClientFromPool(). 
@razitz you're totally right that pings each ms is a lot. Approving the PR :+1: 

@dengliming my goal is to deprecate NewClient and to encourage people to use NewClientFromPool ( and other future client builders ). WDYT?

**Comment by dengliming** [comment]
> my goal is to deprecate NewClient and to encourage people to use NewClientFromPool ( and other future client builders )

@filipecosta90 👍

**Pull request merged**
